### ISSUE TITLE
CMA compilation fails, openSUSE 12.1

### ISSUE THREAD

**Issue by tonycurtis** [Sandia-OpenSHMEM/SOS#139]
If CMA enabled on openSUSE 12.1, compilation fails with

```
make[2]: Entering directory `/home/tonyc/src/sandia/sos/source/src'
  CC       shmem_free_list.lo
  CC       runtime-pmi.lo
  CC       malloc.lo
  CC       init.lo
In file included from shmem_comm.h:51:0,
                 from shmem_synchronization.h:20,
                 from shmem_collectives.h:19,
                 from init.c:30:
transport_cma.h: In function 'process_vm_readv':
transport_cma.h:66:18: error: '__NR_process_vm_readv' undeclared (first use in this function)
transport_cma.h:66:18: note: each undeclared identifier is reported only once for each function it appears in
transport_cma.h: In function 'process_vm_writev':
transport_cma.h:77:18: error: '__NR_process_vm_writev' undeclared (first use in this function)
make[2]: *** [init.lo] Error 1
make[2]: Leaving directory `/home/tonyc/src/sandia/sos/source/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/tonyc/src/sandia/sos/source/src'
make: *** [all-recursive] Error 1
```

(CMA works on openSUSE 13.1)

**Comment by jdinan** [comment]
We seem to be hitting the ```!HAVE_LIBC_CMA``` code that attempts to make the system calls directly.  My guess is that the SUSE 12.1 kernel doesn't support CMA, but that the 13.1 kernel does.

**Comment by tonycurtis** [comment]
The platform I was building on has been zapped and upgraded anyway...
